name = "my-site"
main = "_worker.js"
compatibility_date = "2026-07-27"
keep_vars = true
workers_dev = false
preview_urls = false
routes = [
	{ pattern = "cdn.uxudjs.top", custom_domain = true },
	{ pattern = "static.uxudjs.top", custom_domain = true },
	{ pattern = "app.uxudjs.top", custom_domain = true },
	{ pattern = "m.uxudjs.top", custom_domain = true },
	{ pattern = "api.uxudjs.top", custom_domain = true },
]

[vars]
URL = "https://cloudflare-error-page-3th.pages.dev"

[[kv_namespaces]]
binding = "KV"
id = "39c582f3fc624f96b54d74bfc0faef44"
